/**
 * Airbending: the lowest damage and the lowest HP, and by far the most
 * dangerous positioning in the game. An airbender wins fights by shoving
 * people into fire, off ledges, and out of formation.
 */

import type { Ability } from '../../core/types';
import { ability, allyTarget, blast, cone, enemyTarget, selfTarget, tileTarget } from './helpers';

export const AIR_ABILITIES: readonly Ability[] = [
  ability({
    id: 'air_blast',
    name: 'Air Blast',
    element: 'air',
    apCost: 1,
    range: 6,
    targeting: enemyTarget,
    effects: [
      { kind: 'damage', base: 3, scale: 0.5, damageType: 'air' },
      { kind: 'push', distance: 2 },
    ],
    description: 'A hard shove of wind. Pushes two tiles — pick where they land.',
    flavor: 'Into the fire is a legitimate answer.',
    fx: 'fx.air.blast',
    tags: ['attack', 'control'],
  }),
  ability({
    id: 'air_scooter',
    name: 'Air Scooter',
    element: 'air',
    apCost: 1,
    range: 6,
    targeting: tileTarget,
    cooldown: 2,
    requiresLineOfSight: false,
    effects: [{ kind: 'dash' }],
    description: 'A ball of spinning air. Move anywhere in range, ignoring what is in the way.',
    flavor: 'Invented by a twelve-year-old. Still unbeaten.',
    fx: 'fx.air.scooter',
    tags: ['mobility'],
  }),
  ability({
    id: 'gust',
    name: 'Gust',
    element: 'air',
    apCost: 2,
    range: 4,
    targeting: cone(3),
    effects: [
      { kind: 'damage', base: 4, scale: 0.5, damageType: 'air' },
      { kind: 'push', distance: 1 },
      { kind: 'status', status: 'blinded', duration: 2, chance: 0.4, to: 'hit' },
    ],
    description: 'A fan of dust and wind. Blinds, and scatters steam and fire.',
    flavor: 'Wind also feeds a fire. Watch what you fan.',
    fx: 'fx.air.gust',
    tags: ['attack', 'control'],
  }),
  ability({
    id: 'cyclone',
    name: 'Cyclone',
    element: 'air',
    apCost: 3,
    range: 6,
    targeting: blast(1),
    cooldown: 3,
    effects: [
      { kind: 'damage', base: 6, scale: 0.7, damageType: 'air' },
      { kind: 'pull', distance: 2 },
      { kind: 'status', status: 'slowed', duration: 2, chance: 0.6, to: 'hit' },
    ],
    description: 'A spinning column that drags everything nearby into the middle.',
    flavor: 'Gather them up, then let the earthbender drop a rock on the pile.',
    fx: 'fx.air.cyclone',
    tags: ['attack', 'control'],
  }),
  ability({
    id: 'air_cushion',
    name: 'Air Cushion',
    element: 'air',
    apCost: 2,
    range: 5,
    targeting: allyTarget,
    cooldown: 2,
    effects: [
      { kind: 'heal', base: 4, scale: 0.3 },
      { kind: 'status', status: 'guarded', duration: 1, chance: 1, to: 'hit' },
      { kind: 'grantAp', amount: 1, to: 'hit' },
    ],
    description: 'Catch a friend on a cushion of air: soften the blow and give them an AP.',
    flavor: 'Helping is a technique too.',
    fx: 'fx.air.cushion',
    tags: ['heal', 'buff'],
  }),
  ability({
    id: 'sonic_boom',
    name: 'Sonic Boom',
    element: 'air',
    apCost: 2,
    range: 7,
    targeting: enemyTarget,
    cooldown: 2,
    effects: [
      { kind: 'damage', base: 7, scale: 0.7, damageType: 'air' },
      { kind: 'status', status: 'stunned', duration: 1, chance: 0.3, to: 'hit' },
    ],
    description: 'A clap of compressed air. Sometimes it just switches someone off.',
    flavor: 'Loud, in every sense.',
    fx: 'fx.air.boom',
  }),
  ability({
    id: 'tornado',
    name: 'Tornado',
    element: 'air',
    apCost: 3,
    range: 7,
    targeting: blast(2),
    cooldown: 4,
    effects: [
      { kind: 'damage', base: 7, scale: 0.8, damageType: 'air' },
      { kind: 'push', distance: 3 },
      { kind: 'status', status: 'blinded', duration: 2, chance: 0.75, to: 'hit' },
      { kind: 'status', status: 'slowed', duration: 2, chance: 0.5, to: 'hit' },
    ],
    description: 'A full funnel. Throws everything in a wide area three tiles outward.',
    flavor: 'The air is never still. It only waits.',
    fx: 'fx.air.tornado',
    tags: ['attack', 'control', 'signature'],
  }),
  ability({
    id: 'air_shield',
    name: 'Air Shield',
    element: 'air',
    apCost: 1,
    range: 0,
    targeting: selfTarget,
    cooldown: 2,
    effects: [
      { kind: 'status', status: 'guarded', duration: 1, chance: 1, to: 'self' },
      { kind: 'cleanse', statuses: ['burning'] },
    ],
    description: 'A sphere of moving air. Cheap, brief, and puts out flames.',
    flavor: 'Evade first. Always.',
    fx: 'fx.air.shield',
    tags: ['buff'],
  }),
];
