/**
 * Earthbending: the wall the rest of the party hides behind. Highest HP and
 * defence, lowest speed, and the only element that can rewrite the map's
 * geometry mid-fight.
 */

import type { Ability } from '../../core/types';
import { ability, blast, enemyTarget, line, selfTarget, tileTarget } from './helpers';

export const EARTH_ABILITIES: readonly Ability[] = [
  ability({
    id: 'rock_throw',
    name: 'Rock Throw',
    element: 'earth',
    apCost: 1,
    range: 5,
    targeting: enemyTarget,
    effects: [{ kind: 'damage', base: 5, scale: 0.6, damageType: 'earth' }],
    description: 'Rip a stone out of the ground and put it through someone.',
    flavor: 'Simple. Heavy. Effective.',
    fx: 'fx.earth.rock',
  }),
  ability({
    id: 'earth_wall',
    name: 'Earth Wall',
    element: 'earth',
    apCost: 2,
    range: 5,
    targeting: line(3),
    cooldown: 3,
    effects: [{ kind: 'wall', duration: 3 }],
    description: 'Raises a three-tile stone wall. Blocks movement and line of sight.',
    flavor: 'Neutral jing: wait, listen, then make the ground do the work.',
    fx: 'fx.earth.wall',
    tags: ['control', 'surface'],
  }),
  ability({
    id: 'shockwave',
    name: 'Shockwave',
    element: 'earth',
    apCost: 2,
    range: 2,
    targeting: blast(2),
    cooldown: 2,
    effects: [
      { kind: 'damage', base: 5, scale: 0.5, damageType: 'earth' },
      { kind: 'push', distance: 1 },
      { kind: 'status', status: 'slowed', duration: 2, chance: 0.5, to: 'hit' },
    ],
    description: 'Stamp hard. Everything nearby is knocked back a tile and staggered.',
    flavor: 'Does not care whose side you are on. Check your footing.',
    fx: 'fx.earth.shockwave',
    tags: ['attack', 'control'],
  }),
  ability({
    id: 'mudslide',
    name: 'Mudslide',
    element: 'earth',
    apCost: 3,
    range: 6,
    targeting: blast(2),
    cooldown: 3,
    effects: [
      { kind: 'damage', base: 4, scale: 0.4, damageType: 'earth' },
      { kind: 'surface', surface: 'mud', duration: 4, area: 'area' },
      { kind: 'status', status: 'rooted', duration: 2, chance: 0.4, to: 'hit' },
    ],
    description: 'Churns a wide patch into deep mud. Slow to cross, easy to get stuck in.',
    flavor: 'Half of winning a fight is choosing where it happens.',
    fx: 'fx.earth.mudslide',
    tags: ['control', 'surface'],
  }),
  ability({
    id: 'seismic_sense',
    name: 'Seismic Sense',
    element: 'earth',
    apCost: 1,
    range: 0,
    targeting: selfTarget,
    cooldown: 3,
    effects: [
      { kind: 'revealSurfaces' },
      { kind: 'status', status: 'inspired', duration: 2, chance: 1, to: 'self' },
      { kind: 'cleanse', statuses: ['blinded'] },
    ],
    description: 'Feel the whole field through your feet. See through smoke; aim true.',
    flavor: 'Toph did it better. Everybody does it worse.',
    fx: 'fx.earth.sense',
    tags: ['buff'],
  }),
  ability({
    id: 'boulder',
    name: 'Boulder',
    element: 'earth',
    apCost: 3,
    range: 7,
    targeting: blast(1),
    cooldown: 3,
    effects: [
      { kind: 'damage', base: 9, scale: 0.9, damageType: 'earth' },
      { kind: 'surface', surface: 'rubble', duration: -1, area: 'area' },
    ],
    description: 'A house-sized rock. Leaves rubble that everyone can fight behind.',
    flavor: 'Aim for the middle of the group.',
    fx: 'fx.earth.boulder',
    tags: ['attack', 'surface'],
  }),
  ability({
    id: 'metalbending',
    name: 'Metalbending',
    element: 'earth',
    apCost: 3,
    range: 6,
    targeting: enemyTarget,
    cooldown: 4,
    effects: [
      { kind: 'damage', base: 11, scale: 1, damageType: 'earth', ignoreDefense: true },
      { kind: 'status', status: 'rooted', duration: 2, chance: 1, to: 'hit' },
      { kind: 'status', status: 'stunned', duration: 1, chance: 0.35, to: 'hit' },
    ],
    description: 'Seize the metal on them — armour, blade, driller — and crush it inward.',
    flavor: 'There is earth inside the metal. Find it.',
    fx: 'fx.earth.metal',
    tags: ['attack', 'control', 'signature'],
  }),
  ability({
    id: 'stone_stance',
    name: 'Stone Stance',
    element: 'earth',
    apCost: 1,
    range: 0,
    targeting: selfTarget,
    cooldown: 2,
    effects: [{ kind: 'status', status: 'guarded', duration: 2, chance: 1, to: 'self' }],
    description: 'Root down and armour up.',
    flavor: 'Immovable is a kind of attack.',
    fx: 'fx.earth.stance',
    tags: ['buff'],
  }),
  // The bandit earthbender and the driller both scatter cover around.
  ability({
    id: 'raise_rubble',
    name: 'Raise Rubble',
    element: 'earth',
    apCost: 2,
    range: 5,
    targeting: tileTarget,
    cooldown: 2,
    effects: [{ kind: 'surface', surface: 'rubble', duration: -1, area: 'center' }],
    description: 'Heave a pile of broken stone up out of the ground for cover.',
    flavor: 'Quarry work, weaponised.',
    fx: 'fx.earth.rubble',
    tags: ['surface'],
  }),
];
