/**
 * Waterbending: the party's only real healing, plus the two setup tools that
 * make every other element better — soaking a target for the firebender's
 * lightning, and freezing a puddle under an advancing line.
 */

import type { Ability } from '../../core/types';
import { ability, allyTarget, blast, cone, enemyTarget, line } from './helpers';

export const WATER_ABILITIES: readonly Ability[] = [
  ability({
    id: 'water_whip',
    name: 'Water Whip',
    element: 'water',
    apCost: 1,
    range: 5,
    targeting: enemyTarget,
    effects: [
      { kind: 'damage', base: 4, scale: 0.6, damageType: 'water' },
      { kind: 'status', status: 'wet', duration: 2, chance: 0.75, to: 'hit' },
    ],
    description: 'A lash of water that soaks what it hits. Set up the firebender.',
    flavor: 'Wet things freeze. Wet things conduct. Remember that.',
    fx: 'fx.water.whip',
    tags: ['attack', 'control'],
  }),
  ability({
    id: 'healing_stream',
    name: 'Healing Stream',
    element: 'water',
    apCost: 2,
    range: 4,
    targeting: allyTarget,
    cooldown: 1,
    requiresLineOfSight: true,
    effects: [
      { kind: 'heal', base: 8, scale: 0.8 },
      { kind: 'cleanse', statuses: ['burning', 'blinded'] },
    ],
    description: 'Glowing water knits a friend back together and puts out fires.',
    flavor: 'The rarest gift in the North, and it is not a weapon.',
    fx: 'fx.water.heal',
    tags: ['heal'],
  }),
  ability({
    id: 'water_pull',
    name: 'Water Pull',
    element: 'water',
    apCost: 2,
    range: 6,
    targeting: enemyTarget,
    effects: [
      { kind: 'damage', base: 4, scale: 0.4, damageType: 'water' },
      { kind: 'pull', distance: 3 },
      { kind: 'status', status: 'wet', duration: 2, chance: 1, to: 'hit' },
    ],
    description: 'Hooks an enemy and drags them three tiles toward you. Soaks them too.',
    flavor: 'Come here.',
    fx: 'fx.water.pull',
    tags: ['control'],
  }),
  ability({
    id: 'ice_spikes',
    name: 'Ice Spikes',
    element: 'water',
    apCost: 2,
    range: 6,
    targeting: blast(1),
    cooldown: 2,
    effects: [
      { kind: 'damage', base: 6, scale: 0.7, damageType: 'cold' },
      { kind: 'status', status: 'chilled', duration: 2, chance: 0.7, to: 'hit' },
      { kind: 'surface', surface: 'ice', duration: 2, area: 'area' },
    ],
    description: 'Spears of ice erupt in a small area and leave the ground slick.',
    flavor: 'Chill something twice and it stops moving altogether.',
    fx: 'fx.water.spikes',
    tags: ['attack', 'control', 'surface'],
  }),
  ability({
    id: 'tidal_wave',
    name: 'Tidal Wave',
    element: 'water',
    apCost: 3,
    range: 5,
    targeting: cone(4),
    cooldown: 4,
    effects: [
      { kind: 'damage', base: 7, scale: 0.7, damageType: 'water' },
      { kind: 'push', distance: 2 },
      { kind: 'status', status: 'wet', duration: 3, chance: 1, to: 'hit' },
      { kind: 'surface', surface: 'water', duration: 3, area: 'area' },
    ],
    description: 'A wall of water that shoves everything back and floods the ground.',
    flavor: 'Then ask the firebender to make some lightning.',
    fx: 'fx.water.wave',
    tags: ['attack', 'control', 'surface', 'signature'],
  }),
  ability({
    id: 'ice_shield',
    name: 'Ice Shield',
    element: 'water',
    apCost: 2,
    range: 4,
    targeting: allyTarget,
    cooldown: 3,
    effects: [
      { kind: 'status', status: 'guarded', duration: 2, chance: 1, to: 'hit' },
      { kind: 'heal', base: 3, scale: 0.2 },
    ],
    description: 'A curved plate of ice in front of a friend. Absorbs a lot.',
    flavor: 'Thicker than it looks.',
    fx: 'fx.water.shield',
    tags: ['buff', 'heal'],
  }),
  ability({
    id: 'octopus_form',
    name: 'Octopus Form',
    element: 'water',
    apCost: 3,
    range: 2,
    targeting: blast(2),
    cooldown: 4,
    effects: [
      { kind: 'damage', base: 8, scale: 0.8, damageType: 'water' },
      { kind: 'status', status: 'wet', duration: 3, chance: 1, to: 'hit' },
      { kind: 'status', status: 'guarded', duration: 2, chance: 1, to: 'self' },
      { kind: 'push', distance: 1 },
    ],
    description: 'Six arms of water lash out in every direction while you stay covered.',
    flavor: 'Attack and defence are the same motion.',
    fx: 'fx.water.octopus',
    tags: ['attack', 'buff', 'signature'],
  }),
  // The level-2 utility unlock for both waterbenders.
  ability({
    id: 'ice_path',
    name: 'Ice Path',
    element: 'water',
    apCost: 2,
    range: 5,
    targeting: line(4),
    cooldown: 2,
    effects: [{ kind: 'surface', surface: 'ice', duration: 3, area: 'area' }],
    description: 'Freezes a line of ground solid. Water under it locks up.',
    flavor: 'A road, or a trap, depending who walks it.',
    fx: 'fx.water.path',
    tags: ['surface', 'control'],
  }),

  /* ------------------------------------------------------------------ */
  /* Healing discipline                                                  */
  /* ------------------------------------------------------------------ */

  ability({
    id: 'healing_hands',
    name: 'Healing Hands',
    element: 'water',
    apCost: 2,
    range: 1,
    targeting: allyTarget,
    cooldown: 1,
    effects: [
      { kind: 'heal', base: 14, scale: 1 },
      { kind: 'cleanse', statuses: ['burning', 'chilled', 'blinded'] },
    ],
    description:
      'Hands on, water glowing. Nearly twice what Healing Stream gives, but you have to be standing next to them.',
    flavor: 'Close enough to hear them breathing. That is the point.',
    fx: 'fx.water.hands',
    tags: ['heal'],
  }),
  ability({
    id: 'purifying_mist',
    name: 'Purifying Mist',
    element: 'water',
    apCost: 3,
    range: 5,
    targeting: blast(1),
    cooldown: 3,
    effects: [
      { kind: 'heal', base: 8, scale: 0.6 },
      { kind: 'cleanse', statuses: ['burning', 'blinded', 'shocked', 'chiBlocked'] },
      { kind: 'surface', surface: 'steam', duration: 2, area: 'area' },
    ],
    description:
      'A cloud of warm mist over the whole group: heals everyone friendly inside it, and clears a chi block.',
    flavor: 'Breathe in. You are all right.',
    fx: 'fx.water.mist',
    tags: ['heal', 'surface'],
  }),
  ability({
    id: 'life_tide',
    name: 'Life Tide',
    element: 'water',
    apCost: 3,
    range: 6,
    targeting: blast(2),
    cooldown: 5,
    effects: [
      { kind: 'heal', base: 18, scale: 1.2 },
      {
        kind: 'cleanse',
        statuses: [
          'burning',
          'wet',
          'chilled',
          'frozen',
          'shocked',
          'stunned',
          'slowed',
          'blinded',
          'rooted',
          'chiBlocked',
        ],
      },
      { kind: 'status', status: 'inspired', duration: 2, chance: 1, to: 'allies' },
    ],
    description:
      'Everything the healer has, poured out at once: a large heal across the whole party, every debuff gone, and everyone hits harder for two rounds.',
    flavor: 'Not a technique. A decision.',
    fx: 'fx.water.tide',
    tags: ['heal', 'buff', 'signature'],
  }),
];
